name: Generate ASCII Artbook

on: [push]

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Executeing Shell Script
        run: |
          chmod +x asci-script.sh 
          ./asci-script.sh
